'use strict';
const palette=originalData.settings.palette;
const lenses=[['ac','Asset class'],['tree','Hierarchy'],['sec','Sector'],['mc','Market cap'],['geo','Geography'],['th','Theme'],['cr','Credit & duration'],['cu','Core / Satellite']];
let activeLens='ac',fundMode=originalData.settings.fundMode;
try{fundMode=localStorage.getItem('portfolio-fund-mode')||fundMode}catch{}
if(!['look','tag'].includes(fundMode))fundMode='look';
function signed(n){const rounded=Math.round(n*10)/10;return (rounded>0?'+':'')+fmt(rounded)}
function leafValues(d){return entries(d.allocations).filter(x=>!x.node.children.length).map(x=>({name:x.node.name,value:x.node.target,category:x.key.split(' / ')[0]}))}
// Market cap and geography are recorded only where they describe the instrument
// itself: a fund's are a property of what it holds. In Single tag mode, where the
// whole fund counts in one bucket, fall back to its largest underlying bucket
// rather than reporting it as unclassified.
function dominantBucket(s,key){
 const weights=s.lookThrough?.[key];
 if(!weights?.length)return null;
 return weights.reduce((best,x)=>x.weight>best.weight?x:best).bucket;
}
function exposure(values,lens){
 const buckets=new Map();let total=0,missing=0;
 for(const h of values){
  const s=originalData.securities.find(s=>s.name===h.name);
  if(lens==='cr'&&!(s?.tags.isDebt||(!s&&h.category==='Fixed income')))continue;
  total+=h.value;let parts;
  if(!s){parts=[['Unclassified',1]];missing+=h.value}
  else if(lens==='sec')parts=fundMode==='look'&&s.lookThrough?s.lookThrough.sector.map(x=>[x.bucket,x.weight]):[[s.tags.sector||'Unclassified',1]];
  else if(lens==='mc'||lens==='geo'){const key=lens==='mc'?'marketCap':'geography';parts=fundMode==='look'&&s.lookThrough?s.lookThrough[key].map(x=>[x.bucket,x.weight]):[[s.tags[key]||dominantBucket(s,key)||'Unclassified',1]]}
  else if(lens==='th')parts=(s.tags.themes.length?s.tags.themes:['Unclassified']).map(x=>[x,1]);
  else if(lens==='cr')parts=[[(s.tags.creditQuality||'Unclassified')+' / '+(s.tags.duration||'Unclassified'),1]];
  else parts=[[s.tags.custom||'Unclassified',1]];
  for(const [key,weight] of parts)buckets.set(key,(buckets.get(key)||0)+h.value*weight);
 }
 return {buckets,total,missing};
}
function exposureRows(actual,target,lens){const a=exposure(actual,lens),t=exposure(target,lens);return [...new Set([...a.buckets.keys(),...t.buckets.keys()])].sort().map(name=>({name,actual:a.total>0?(a.buckets.get(name)||0)/a.total*100:null,target:t.total>0?(t.buckets.get(name)||0)/t.total*100:null,value:a.buckets.get(name)||0}))}
let lensControls;
function lensTable(actual,target,lens,isModel=false){const rows=exposureRows(actual,target,lens);return `<div class="tablewrap"><table><thead><tr><th>Exposure</th>${isModel?'':'<th>Actual %</th>'}<th>${isModel?'Model':'Client target'} %</th>${isModel?'':'<th>Drift (pp)</th>'}</tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td>${isModel?'':`<td>${x.actual===null?'Unavailable':fmt(x.actual)}</td>`}<td>${x.target===null?'Not defined':fmt(x.target)}</td>${isModel?'':`<td>${x.actual===null||x.target===null?'—':signed(x.actual-x.target)}</td>`}</tr>`).join('')||'<tr><td colspan="4">No data for this lens.</td></tr>'}</tbody></table></div><p><small>${lens==='cr'?'Percentages use debt only.':lens==='th'?'Themes overlap; their percentages can exceed 100% when added.':'Percentages use the whole portfolio.'} Exposure data is illustrative, extracted from the original mockup. Exposure targets are derived from the selected allocation.</small></p>`}
function lensContent(actual,target,isModel=false){if(activeLens!=='tree')return lensTable(actual,target,activeLens,isModel);return `<p class="note">Hierarchy groups the original asset classes with their exposure dimensions. Geography, market cap and sector are separate views: the source contains no joint underlying-holdings data to combine them reliably.</p>${originalData.assetHierarchy.map(c=>{const aa=actual.filter(x=>x.category===c.n),tt=target.filter(x=>x.category===c.n),dims=c.n==='Equity'?['geo','mc','sec']:c.n==='Fixed income'?['cr']:['sec'];return `<details class="card" open><summary>${esc(c.n)}</summary>${dims.map(l=>`<details class="review-detail"><summary>${lenses.find(x=>x[0]===l)[1]} (% of ${esc(c.n)})</summary>${lensTable(aa,tt,l,isModel).replace('Percentages use the whole portfolio.','Percentages use this asset class.')}</details>`).join('')}</details>`}).join('')}`}
function stack(values){return `<div class="allocation" style="margin:8px 0">${values.map((x,i)=>`<span style="width:${Math.max(0,x)}%;background:${palette[i]}" title="${esc(originalData.assetHierarchy[i].n)} ${fmt(x)}%"></span>`).join('')}</div>`}

let distribution;
function refreshLens(context){context==='model'?render():renderClient()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.lens){activeLens=b.dataset.lens;refreshLens(b.dataset.context)}if(b.dataset.fundMode){fundMode=b.dataset.fundMode;try{localStorage.setItem('portfolio-fund-mode',fundMode)}catch{}refreshLens(b.dataset.context)}});

// Keep version numbers in history only; published snapshots remain immutable internally.
list=function(){selected=null;editing=false;$('footer').innerHTML='';$('app').innerHTML=`<div class="flex between"><div><div class="eyebrow">Investment strategy</div><h1>Models</h1><p class="muted">Reusable allocations, from asset classes to individual investments.</p></div><button class="primary" onclick="newModel()">＋ Create model</button></div><h2>Your model library</h2><div class="card tablewrap"><table><thead><tr><th>Model / intended use</th><th>Portfolios</th><th>State</th><th></th></tr></thead><tbody>${models.map(m=>`<tr><td><button class="link" onclick="openModel('${m.id}')">${esc(latest(m)?.data.name||m.draft?.name||'Untitled model')}</button><br><small>${esc(latest(m)?.data.description||m.draft?.description||'')}</small></td><td>${m.clients.length}</td><td>${m.draft?'Draft changes':'Published'}</td><td><button onclick="openModel('${m.id}')">Open →</button></td></tr>`).join('')}</tbody></table></div><p class="note">Model changes are reviewed before updating an approved client target. Publication details and previous snapshots are available in History.</p>`};
render=function(){const m=current(),d=data(),v=latest(m),issues=validation(d);$('app').innerHTML=`<button class="quiet" onclick="saveAndList()">← All models</button><div class="flex between toolbar"><div><h1>${esc(d.name||'Untitled model')}</h1><p>${esc(d.description)}</p><span class="badge ${editing?'draft':''}">${editing?'Draft':'Published'}</span></div><div class="flex"><button onclick="history()">History</button>${!editing?`<button class="primary" onclick="startEdit()">${m.draft?'Resume draft':'Edit model'}</button>`:''}</div></div><button class="quiet" onclick="clients()">${m.clients.length} portfolios using this model →</button>${editing?`<details class="card"><summary>Model name & intended use</summary><label class="field">Model name<input value="${esc(d.name)}" onchange="data().name=this.value;dirty=true;render()"></label><label class="field">Intended use<textarea onchange="data().description=this.value;dirty=true;render()">${esc(d.description)}</textarea></label></details>`:''}${lensControls('model')}${activeLens==='ac'?`<div class="card"><h2>Target allocation · ${fmt(d.allocations.reduce((s,n)=>s+n.target,0))}%</h2><small>All targets are percentages of the whole portfolio.</small>${stack(originalData.assetHierarchy.map(c=>d.allocations.find(n=>n.name===c.n)?.target||0))}</div><div class="flex toolbar"><button onclick="expandAll()">Expand all</button><button onclick="collapseAll()">Collapse all</button></div><div class="card tablewrap"><table><thead><tr><th>Allocation</th><th>Target %</th><th></th></tr></thead><tbody>${rows(d.allocations)}</tbody></table></div>${editing?'<button onclick="addAllocation()">＋ Add asset class</button>':''}`:`<section class="card"><h2>${lenses.find(x=>x[0]===activeLens)[1]}</h2>${lensContent(leafValues(d),leafValues(d),true)}</section>`}<div class="card ${issues.length?'warning':''}"><h2>${issues.length?'Complete before publishing':'Allocation checks passed'}</h2>${issues.length?'<ul>'+issues.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p>Targets total 100%; child allocations match their parents.</p>'}</div>`;$('footer').innerHTML=editing?`<div class="footer"><div><strong>${dirty?'Changes not saved yet':'Draft workspace'}</strong><small>Approved client targets remain unchanged</small></div><div class="flex"><button onclick="saveDraft()">Save draft</button><button class="primary" onclick="review()" ${issues.length?'disabled':''}>Review & publish →</button></div></div>`:''};
rows=function(ns,depth=0){return ns.map(n=>`<tr class="${depth?'child':'rowtop'}"><td style="padding-left:${12+depth*20}px">${n.children.length?`<button class="chev" aria-label="${expanded.has(n.id)?'Collapse':'Expand'} ${esc(n.name)}" aria-expanded="${expanded.has(n.id)}" onclick="toggle('${n.id}')">${expanded.has(n.id)?'⌄':'›'}</button>`:''}${esc(n.name)}</td><td>${editing?`<input aria-label="${esc(n.name)} target" class="target" type="number" step="0.1" min="0" max="100" value="${n.target}" onchange="changeTarget('${n.id}',this.value)">`:fmt(n.target)+'%'}</td><td>${editing&&depth===0?`<button class="quiet" aria-label="Remove ${esc(n.name)}" onclick="removeNode('${n.id}')">×</button>`:''}</td></tr>${n.children.length&&expanded.has(n.id)?rows(n.children,depth+1):''}`).join('')};
changes=function(before,after){const a=flatten(before),b=flatten(after);let out=[...new Set([...Object.keys(a),...Object.keys(b)])].filter(k=>a[k]?.target!==b[k]?.target).map(k=>`<tr><td>${esc(k)}</td><td>${a[k]?fmt(a[k].target)+'%':'—'}</td><td>${b[k]?fmt(b[k].target)+'%':'Removed'}</td></tr>`).join('');for(const field of ['name','description'])if(before?.[field]!==after[field])out+=`<tr><td>${field==='name'?'Model name':'Intended use'}</td><td>${esc(before?.[field]||'—')}</td><td>${esc(after[field])}</td></tr>`;return out||'<tr><td colspan="3">No allocation changes.</td></tr>'};
review=function(){if(validation(data()).length)return;show(`<h2>Review ${esc(data().name)}</h2><div class="tablewrap"><table><thead><tr><th>Allocation / field</th><th>Published</th><th>Draft</th></tr></thead><tbody>${changes(latest(current())?.data,data())}</tbody></table></div><p class="note">${current().clients.length} portfolios retain their approved targets.</p><label class="field">Reason for this change<textarea id="reason"></textarea></label><p id="publishError" class="errors"></p><div class="actions"><button onclick="closeModal()">Back to draft</button><button class="primary" onclick="publish()">Publish model</button></div>`)};
