'use strict';
const CLIENT_KEY='portfolio-original-targets-v2';
const money=v=>'₹'+fmt(v)+' lakh';
const today=()=>new Date().toLocaleDateString('en-CA');
function entries(tree,path=''){return tree.flatMap(n=>{const key=path?path+' / '+n.name:n.name;return [{key,node:n},...entries(n.children,key)]})}
function scopeValue(plan){return plan.assets.filter(a=>a.included).reduce((s,a)=>s+a.value,0)}
function baseRef(plan){return plan.base.name}
function seedClients(){return originalData.accounts.map(account=>{
 const model=models.find(m=>m.id==='full-model-'+['Conservative','Moderate','Aggressive'].indexOf(account.riskProfile))||models.find(m=>latest(m)?.data.name===account.riskProfile);
 const source={name:account.riskProfile,description:'Original wireframe allocation',allocations:catalogTree(account.riskProfile)};
 const assets=account.holdings.map(h=>{const s=originalData.securities.find(s=>s.id===h.securityId);return {id:account.id+'-'+s.id,securityId:s.id,name:s.name,category:s.assetClass,account:s.subcategory,value:h.valueLakh,costBasis:h.costBasisLakh,included:true,reason:'',liquidity:s.liquidity,sourceDate:originalData.metadata.asOf}});
 return {id:account.id,name:account.name,type:account.type,householdId:account.householdId,household:originalData.households.find(h=>h.id===account.householdId).name,risk:account.riskProfile,threshold:account.originalThresholdPP??originalData.settings.firmThresholdPP,history:[{number:1,approvedAt:'2026-10-03T00:00:00.000Z',effectiveDate:originalData.metadata.asOf,approver:originalData.audit.user,reason:'Initial illustrative target using the original mockup allocation and all original holdings. Approval is a demonstration record.',plan:{base:{modelId:model?.id||null,version:1,name:source.name,data:source},overrides:{},assets}}],draft:null};
})}
let clientRecords,clientStorageOK=true;
try{const saved=localStorage.getItem(CLIENT_KEY);clientRecords=saved?JSON.parse(saved):seedClients();if(!Array.isArray(clientRecords))throw new Error('Invalid records');if(!saved)localStorage.setItem(CLIENT_KEY,JSON.stringify(clientRecords))}catch{clientRecords=seedClients();clientStorageOK=false}
let activeClient=null,clientEditing=false,clientExpanded=new Set(),clientView='households',clientSearch='',modelFilter='',flaggedOnly=false,sortField='drift',sortDirection=-1;
const approved=c=>c.history.at(-1),client=()=>clientRecords.find(c=>c.id===activeClient),planNow=()=>clientEditing?client().draft:approved(client()).plan;
const dashboardExpanded=new Set();
const actualValues=p=>p.assets.filter(a=>a.included).map(a=>({name:a.name,value:a.value,category:a.category}));
function saveClients(){try{localStorage.setItem(CLIENT_KEY,JSON.stringify(clientRecords));clientStorageOK=true;return true}catch{clientStorageOK=false;notify('Browser saving unavailable. Changes remain in this session only.');return false}}
function syncClients(){models.forEach(m=>m.clients=clientRecords.filter(c=>approved(c).plan.base.modelId===m.id).map(c=>({id:c.id,name:c.name,version:approved(c).plan.base.version})))}
function navState(which){for(const [id,key] of [['navClients','portfolios'],['navModels','models'],['navAudit','history']])$(id).setAttribute('aria-current',which===key?'page':'false');document.title='Portfolio Console · '+({portfolios:'Portfolios',models:'Models',history:'Audit log'}[which]||'Portfolios')}
function leaveModels(){if(editing){persist();dirty=false}editing=false}
function clientNav(){leaveModels();activeClient=null;clientEditing=false;navState('portfolios');renderClients()}
function modelNav(){leaveModels();clientEditing=false;syncClients();activeLens='ac';navState('models');list()}
function newer(c){const p=approved(c).plan,m=models.find(m=>m.id===p.base.modelId);return m&&latest(m)?.number>p.base.version}
function effective(plan){const result=copy(plan.base.data);for(const x of entries(result.allocations)){const o=plan.overrides[x.key];if(o?.target!==undefined)x.node.target=o.target}return result}
function targetIssues(plan){const issues=validation(effective(plan));if(scopeValue(plan)<=0)issues.push('Include at least one asset with a positive value.');if(plan.assets.some(a=>!a.included&&!a.reason.trim()))issues.push('Give a reason for each excluded asset.');const keys=new Set(entries(plan.base.data.allocations).map(x=>x.key));if(Object.keys(plan.overrides).some(k=>!keys.has(k)))issues.push('Some customisations do not match the selected model. Keep the earlier model or resolve the allocations before approval.');return issues}
const EXPOSURE_LENSES=['sec','mc','geo','th','cr'];
const lensBandDefault=lens=>originalData.settings.originalLensBands[lens]?.at(-1)||5;
// An approved portfolio limit replaces the implied target and/or the sample band for one bucket.
function effectiveLensLimit(limits,lens,bucket,impliedTarget){
 const o=limits?.[lens]?.[bucket]||{};
 return {target:o.target??impliedTarget,band:o.band??lensBandDefault(lens),impliedTarget,custom:o.target!==undefined||o.band!==undefined};
}
function portfolioMetrics(actual,target,threshold,lensLimits){
 const total=actual.reduce((s,x)=>s+x.value,0),classes=originalData.assetHierarchy.map(c=>({name:c.n,actual:total?actual.filter(x=>x.category===c.n).reduce((s,x)=>s+x.value,0)/total*100:null,target:target.filter(x=>x.category===c.n).reduce((s,x)=>s+x.value,0)}));
 const drift=total?Math.max(...classes.map(x=>Math.abs(x.actual-x.target))):null;
 const exposureFlags=EXPOSURE_LENSES.flatMap(l=>exposureRows(actual,target,l).map(x=>{
  const limit=effectiveLensLimit(lensLimits,l,x.name,x.target);
  return {...x,lens:l,target:limit.target,impliedTarget:limit.impliedTarget,band:limit.band,limitSource:limit.custom?'portfolio':'default',drift:x.actual===null||limit.target===null?null:x.actual-limit.target};
 }).filter(x=>x.drift!==null&&Math.abs(x.drift)>x.band));
 return {total,classes,drift,threshold,exposureFlags,flagged:drift!==null&&(drift>threshold||exposureFlags.length>0)};
}
function dashboardRecords(){
 const accounts=clientRecords.map(c=>{const p=approved(c).plan,actual=actualValues(p),target=leafValues(effective(p));return {id:c.id,name:c.name,risk:c.risk,model:baseRef(p),kind:c.type,members:[c],household:c.household,actual,target,lensLimits:p.lensOverrides,...portfolioMetrics(actual,target,c.threshold,p.lensOverrides)}});
 if(clientView==='accounts')return accounts;
 return originalData.households.map(h=>{const children=accounts.filter(a=>a.members[0].householdId===h.id),total=children.reduce((s,a)=>s+a.total,0),actual=children.flatMap(a=>a.actual),target=children.flatMap(a=>a.target.map(x=>({...x,value:total?x.value*a.total/total:0}))),names=[...new Set(children.map(a=>a.model))];return {id:h.id,name:h.name,risk:h.riskProfile,model:names.length===1?names[0]:'Mixed models',kind:'Household',members:children.flatMap(a=>a.members),household:h.name,actual,target,...portfolioMetrics(actual,target,h.originalThresholdPP??originalData.settings.firmThresholdPP)}});
}
function visibleRecords(){return dashboardRecords().filter(r=>(r.name+' '+r.household+' '+r.members.map(c=>c.name).join(' ')).toLowerCase().includes(clientSearch.toLowerCase())&&(!modelFilter||r.model===modelFilter)&&(!flaggedOnly||r.flagged)).sort((a,b)=>sortDirection*(sortField==='name'?a.name.localeCompare(b.name):(a[sortField]??0)-(b[sortField]??0)))}
let renderClients;
let householdPage;
let openClient;
let editClient;
function modelOptions(p){return models.filter(m=>latest(m)).map(m=>{const mi=models.indexOf(m),v=latest(m);return `<option value="${mi}:${m.versions.length-1}" ${p.base.modelId===m.id?'selected':''}>${esc(v.data.name)}</option>`}).join('')}
function scopePanel(p,scopeOpen){return `<details class="card scope-details" ${scopeOpen?'open':''}><summary>Assets included in comparison</summary><p class="muted">${money(scopeValue(p))} included out of ${money(p.assets.reduce((s,x)=>s+x.value,0))} recorded. The original example includes every asset. Excluding an asset changes the denominator, not its recorded value. Liquidity is a separate property: a Locked asset can still count in the allocation comparison.</p><div class="tablewrap"><table><thead><tr><th>Asset</th><th class="numeric-head">Value (₹ L)</th><th>Liquidity</th><th>Included</th><th>Exclusion reason</th></tr></thead><tbody>${p.assets.map((x,i)=>{const sec=originalData.securities.find(y=>y.name===x.name);return `<tr><td>${esc(x.name)}${sec?.physical?'<span class="holding-tag physical">Physical</span>':''}</td><td class="numeric">${fmt(x.value)}</td><td>${sec?`<span class="state-pill ${sec.liquidity==='Locked'?'over':sec.liquidity==='Semi-liquid'?'under':'ok'}">${esc(sec.liquidity)}</span>`:'—'}</td><td>${clientEditing?`<input type="checkbox" aria-label="Include ${esc(x.name)}" data-scope="${i}" ${x.included?'checked':''}>`:x.included?'Yes':'No'}</td><td>${clientEditing&&!x.included?`<input class="scope-reason" aria-label="Reason for excluding ${esc(x.name)}" data-reason="${i}" value="${esc(x.reason)}">`:esc(x.included?'—':x.reason)}</td></tr>`}).join('')}</tbody></table></div></details>`}
let renderClient;
let targetRows;
function reviewBase(){const [mi,vi]=$('baseChoice').value.split(':').map(Number),m=models[mi],v=m.versions[vi],p=planNow();show(`<h2>Review model selection</h2><p>${esc(baseRef(p))} → ${esc(v.data.name)}</p><p>Existing client adjustments are retained by allocation path. Unmatched adjustments block approval.</p><div class="tablewrap"><table><thead><tr><th>Field</th><th>Previous model allocation</th><th>Selected model allocation</th></tr></thead><tbody>${changes(p.base.data,v.data)}</tbody></table></div><div class="actions"><button onclick="closeModal()">Keep current model</button><button class="primary" data-use-base="${mi}:${vi}">Use in draft</button></div>`)}
function scopeChanges(before,after){const changed=after.assets.filter(x=>{const o=before.assets.find(a=>a.id===x.id);return !o||o.included!==x.included||o.reason!==x.reason});return changed.length?'<ul>'+changed.map(x=>'<li>'+esc(x.name)+': '+(x.included?'Included':'Excluded — '+esc(x.reason))+'</li>').join('')+'</ul>':'<p>No scope changes.</p>'}
function reviewClient(){const p=planNow(),old=approved(client()).plan;if(targetIssues(p).length)return;show(`<h2>Review client target</h2><p>${esc(client().name)}</p><p>Model: ${esc(baseRef(old))} → ${esc(baseRef(p))}</p><p>Included value: ${money(scopeValue(old))} → ${money(scopeValue(p))}</p><h3>Scope changes</h3>${scopeChanges(old,p)}<h3>Allocation changes</h3><div class="tablewrap"><table><thead><tr><th>Field</th><th>Approved target</th><th>Proposed target</th></tr></thead><tbody>${changes(effective(old),effective(p))}</tbody></table></div><label class="field">Approval reason<textarea id="targetReason"></textarea></label><label class="field">Approver<input id="targetApprover" value="${esc(originalData.audit.user)}"></label><p class="note">Illustrative approval, effective today (${esc(today())}).</p><p id="targetError" class="errors"></p><div class="actions"><button onclick="closeModal()">Back to draft</button><button class="primary" data-action="approve">Approve client target</button></div>`)}
function approveClient(){const reason=$('targetReason').value.trim(),approver=$('targetApprover').value.trim();if(!reason||!approver){$('targetError').textContent='Enter a reason and approver.';return}if(targetIssues(planNow()).length)return;const c=client();c.history.push({number:approved(c).number+1,approvedAt:new Date().toISOString(),effectiveDate:today(),approver,reason,plan:copy(c.draft)});c.draft=null;saveClients();syncClients();clientEditing=false;closeModal();renderClient();notify('Client target approved. Other targets and actual holdings are unchanged.')}
function historyMarkup(c){return [...c.history].reverse().map(h=>`<details class="history"><summary>Target revision ${h.number} · effective ${esc(h.effectiveDate)}</summary><p>${esc(h.reason)}</p><p><small>${esc(h.approver)} · ${esc(h.approvedAt)} · ${esc(h.plan.base.name)} model revision ${h.plan.base.version}</small></p><p>Included value: ${money(scopeValue(h.plan))}</p><div class="tablewrap"><table><thead><tr><th>Allocation</th><th>Target %</th></tr></thead><tbody>${entries(effective(h.plan).allocations).map(x=>`<tr><td>${esc(x.key)}</td><td>${fmt(x.node.target)}</td></tr>`).join('')}</tbody></table><table><thead><tr><th>Scope asset</th><th>Value</th><th>Inclusion / reason</th></tr></thead><tbody>${h.plan.assets.map(x=>`<tr><td>${esc(x.name)}</td><td>${money(x.value)}</td><td>${x.included?'Included':'Excluded: '+esc(x.reason)}</td></tr>`).join('')}</tbody></table></div></details>`).join('')}
function clientHistory(){show(`<h2>Target history · ${esc(client().name)}</h2>${historyMarkup(client())}<div class="actions"><button onclick="closeModal()">Close</button></div>`)}
function auditPage(){leaveModels();clientEditing=false;navState('history');$('footer').innerHTML='';let earlier=[];try{earlier=JSON.parse(localStorage.getItem('portfolio-original-targets-v1')||localStorage.getItem('portfolio-client-targets-v1')||'[]')}catch{}$('app').innerHTML=`<div class="eyebrow">Audit trail</div><h1>Audit log</h1><p class="muted">Model publications and client target approvals across every portfolio. Revision details are kept here.</p><h2>Models</h2>${models.map(m=>`<details class="card"><summary>${esc(latest(m)?.data.name||m.draft?.name)}</summary>${[...m.versions].reverse().map(v=>`<details class="history"><summary>Revision ${v.number} · ${esc(v.date)}</summary><p>${esc(v.reason)}</p><div class="tablewrap"><table><thead><tr><th>Allocation</th><th>Target %</th></tr></thead><tbody>${Object.entries(flatten(v.data)).map(([k,n])=>`<tr><td>${esc(k)}</td><td>${fmt(n.target)}</td></tr>`).join('')}</tbody></table></div></details>`).join('')}</details>`).join('')}<h2>Portfolio targets</h2>${clientRecords.map(c=>`<details class="card"><summary>${esc(c.name)}</summary>${historyMarkup(c)}</details>`).join('')}${earlier.length?`<details class="card"><summary>Earlier prototype examples · ${earlier.length} records retained</summary><p>These invented examples have been replaced in the portfolio list by the original sample accounts. Saved drafts and approvals remain available here.</p>${earlier.map(c=>`<details class="history"><summary>${esc(c.name)}</summary>${historyMarkup(c)}${c.draft?`<details><summary>Saved draft</summary><div class="tablewrap"><table><tbody>${entries(effective(c.draft).allocations).map(x=>`<tr><td>${esc(x.key)}</td><td>${fmt(x.node.target)}%</td></tr>`).join('')}</tbody></table></div></details>`:''}</details>`).join('')}</details>`:''}`}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(b.dataset.client){closeModal();openClient(b.dataset.client);return}if(b.dataset.household){householdPage(b.dataset.household);return}if(b.dataset.sort){sortDirection=sortField===b.dataset.sort?-sortDirection:1;sortField=b.dataset.sort;renderClients();return}if(b.dataset.toggle!==undefined){const key=entries(planNow().base.data.allocations)[+b.dataset.toggle].key;clientExpanded.has(key)?clientExpanded.delete(key):clientExpanded.add(key);renderClient();return}if(b.dataset.useBase){const [mi,vi]=b.dataset.useBase.split(':').map(Number),m=models[mi],v=m.versions[vi];client().draft.base={modelId:m.id,version:v.number,name:v.data.name,data:copy(v.data)};saveClients();closeModal();renderClient();return}if(!a)return;({accounts:()=>{clientView='accounts';renderClients()},households:()=>{clientView='households';renderClients()},back:clientNav,edit:editClient,approved:()=>{clientEditing=false;renderClient()},expand:()=>{clientExpanded=new Set(entries(planNow().base.data.allocations).map(x=>x.key));renderClient()},collapse:()=>{clientExpanded.clear();renderClient()},base:reviewBase,review:reviewClient,approve:approveClient,history:clientHistory}[a]||(()=>{}))()});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='clientSearch'){clientSearch=t.value;renderClients();return}if(t.id==='modelFilter'){modelFilter=t.value;renderClients();return}if(t.id==='flaggedOnly'){flaggedOnly=t.checked;renderClients();return}if(!clientEditing)return;const p=planNow();if(t.dataset.adjust!==undefined){const key=entries(p.base.data.allocations)[+t.dataset.adjust].key;p.overrides[key]=p.overrides[key]||{};if(t.value==='')delete p.overrides[key].target;else p.overrides[key].target=Number(t.value);if(!Object.keys(p.overrides[key]).length)delete p.overrides[key]}else if(t.dataset.scope!==undefined){p.assets[+t.dataset.scope].included=t.checked}else if(t.dataset.reason!==undefined){p.assets[+t.dataset.reason].reason=t.value}else return;saveClients();renderClient()});
clients=function(){syncClients();const m=current();show(`<h2>Portfolios using ${esc(latest(m)?.data.name)}</h2><p>Approved targets remain fixed until reviewed.</p>${m.clients.map(c=>`<p><button data-client="${c.id}">${esc(c.name)} →</button></p>`).join('')||'<p>No portfolios assigned.</p>'}<div class="actions"><button onclick="closeModal()">Close</button></div>`)};
// Navigation starts after all workspace scripts load.

let dashboardRow;
function showHolding(id){
 const asset=planNow().assets.find(a=>a.id===id),s=originalData.securities.find(s=>s.id===asset?.securityId);if(!asset||!s)return;
 show(`<h2>${esc(asset.name)}</h2><p>${esc(s.assetClass)} / ${esc(s.subcategory)} · ${s.physical?'Physical asset':'Financial instrument'}</p><div class="tablewrap"><table><tbody><tr><th>Original recorded value</th><td>${money(asset.value)}</td></tr><tr><th>Illustrative cost basis</th><td>${money(asset.costBasis)}</td></tr><tr><th>Illustrative unrealised gain</th><td>${money(asset.value-asset.costBasis)}</td></tr><tr><th>Original placeholder tax rate</th><td>${s.illustrativeTaxRatePercent}%</td></tr><tr><th>Liquidity</th><td>${esc(s.liquidity)}</td></tr></tbody></table></div><p class="note">${esc(s.originalNote)} These notes and rates are unverified placeholders from the original mockup, not current tax guidance.</p><h3>Original classification</h3><p>${esc(s.tags.sector)} / ${esc(s.tags.subsector)} · ${esc(s.tags.marketCap)} · ${esc(s.tags.geography)}</p><p>Themes: ${esc(s.tags.themes.join(', '))} · ${esc(s.tags.custom)}</p>${s.lookThrough?`<details><summary>Illustrative underlying exposures</summary>${Object.entries(s.lookThrough).map(([dimension,items])=>`<h3>${esc(dimension)}</h3>${items.map(x=>`<p>${esc(x.bucket||x.sector+' / '+x.subsector)}: ${fmt(x.weight*100)}%</p>`).join('')}`).join('')}</details>`:''}<div class="actions"><button onclick="closeModal()">Close</button></div>`);
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.dashboardExpand){const id=b.dataset.dashboardExpand;dashboardExpanded.has(id)?dashboardExpanded.delete(id):dashboardExpanded.add(id);renderClients()}if(b.dataset.holding)showHolding(b.dataset.holding)});
