// Publish a branch into a subdirectory of the GitHub Pages site, so work in
// progress can be shown without touching what is live at the root.
//
//   node scripts/publish-preview.cjs <git-ref> [directory]
//   node scripts/publish-preview.cjs naveenravindran92/revised-mockup-v3 v3
//
// The directory is rebuilt from scratch each time, so re-running it after the
// branch moves is the whole refresh procedure. Only the files the site needs to
// run are copied: no tests, scripts or documentation.
//
// Two edits are made to the copy, both deliberate:
//
//  1. A marker in the prototype bar, so nobody mistakes the preview for the
//     live site.
//  2. A namespaced localStorage facade. GitHub Pages serves both versions from
//     one origin, and localStorage is scoped per origin rather than per path,
//     so without this the preview and the live site would share saved models,
//     client targets and plans. An edit in one would silently change the other.
const fs = require('node:fs');
const path = require('node:path');
const {execFileSync} = require('node:child_process');

const root = path.join(__dirname, '..');
const ref = process.argv[2];
const directory = process.argv[3] || 'v3';
if (!ref) {
 process.stderr.write('Usage: node scripts/publish-preview.cjs <git-ref> [directory]\n');
 process.exit(1);
}

const git = (...args) => execFileSync('git', args, {cwd: root, encoding: 'utf8', maxBuffer: 1 << 28});
const gitBuffer = (...args) => execFileSync('git', args, {cwd: root, maxBuffer: 1 << 28});

// The site is the root-level markup, scripts and styles plus the data they
// fetch. Everything else in the repository is for building, testing or reading.
const isRuntimeFile = file => {
 if (file.startsWith('data/')) return file.endsWith('.json');
 if (file.includes('/')) return false;
 return /\.(html|js|css)$/.test(file);
};

const files = git('ls-tree', '-r', '--name-only', ref).split('\n').filter(Boolean).filter(isRuntimeFile);
if (!files.length) throw new Error('No runtime files found at ' + ref);

// path.join would silently reinterpret an absolute path as repository-relative,
// so a throwaway build aimed at /tmp would land inside the repository instead.
const target = path.resolve(root, directory);
if (!path.isAbsolute(directory) && (directory.startsWith('..') || !target.startsWith(root + path.sep))) {
 throw new Error('Refusing to write outside the repository: ' + directory);
}
fs.rmSync(target, {recursive: true, force: true});
for (const file of files) {
 const destination = path.join(target, file);
 fs.mkdirSync(path.dirname(destination), {recursive: true});
 fs.writeFileSync(destination, gitBuffer('show', ref + ':' + file));
}

const namespace = directory + '-preview';
const STORAGE_SHIM = `/* Generated by scripts/publish-preview.cjs. Do not edit here.
   The preview and the live site share an origin, so they would otherwise share
   localStorage: saving a model or approving a target on one would change the
   other. Every key this copy reads or writes is namespaced instead. */
(function(){
 var PREFIX=${JSON.stringify(namespace + ':')};
 var real;
 try{real=window.localStorage}catch(e){return}
 if(!real)return;
 var ours=function(){return Object.keys(real).filter(function(k){return k.indexOf(PREFIX)===0})};
 var facade={
  getItem:function(k){return real.getItem(PREFIX+k)},
  setItem:function(k,v){return real.setItem(PREFIX+k,v)},
  removeItem:function(k){return real.removeItem(PREFIX+k)},
  clear:function(){ours().forEach(function(k){real.removeItem(k)})},
  key:function(i){var k=ours()[i];return k===undefined?null:k.slice(PREFIX.length)},
  get length(){return ours().length}
 };
 try{Object.defineProperty(window,'localStorage',{configurable:true,get:function(){return facade}})}
 catch(e){/* An older browser keeps the shared store; the banner still says this is a preview. */}
})();
`;
fs.writeFileSync(path.join(target, 'preview-storage.js'), STORAGE_SHIM);

const indexPath = path.join(target, 'index.html');
let index = fs.readFileSync(indexPath, 'utf8');

// Load the shim before anything that might read storage.
const bootstrap = /<script src="bootstrap\.js[^"]*"><\/script>/;
if (!bootstrap.test(index)) throw new Error('Could not find the bootstrap script tag to anchor the storage shim');
index = index.replace(bootstrap, m => '<script src="preview-storage.js"></script>' + m);

// Say what this is, in the bar that already says what the prototype is.
const banner = 'INTERACTIVE PROTOTYPE · Illustrative allocations and client records';
if (!index.includes(banner)) throw new Error('Could not find the prototype bar to mark as a preview');
index = index.replace(banner, 'PREVIEW BUILD · ' + banner + ' · <a href="../" style="color:inherit">open the current release</a>');
index = index.replace('<title>Portfolio Console · Models</title>', '<title>Portfolio Console · preview</title>');

fs.writeFileSync(indexPath, index);

const describe = git('rev-parse', '--short', ref).trim();
fs.writeFileSync(path.join(target, 'PREVIEW.txt'),
 `Generated by scripts/publish-preview.cjs\nref: ${ref}\ncommit: ${describe}\nfiles: ${files.length}\n` +
 `\nThis directory is generated. Edit the branch and re-run the script; do not edit here.\n`);

process.stderr.write(`published ${files.length} files from ${ref} (${describe}) into ${directory}/\n`);
