/* Generated by scripts/publish-preview.cjs. Do not edit here.
   The preview and the live site share an origin, so they would otherwise share
   localStorage: saving a model or approving a target on one would change the
   other. Every key this copy reads or writes is namespaced instead. */
(function(){
 var PREFIX="/tmp/preview-probe-preview:";
 var real;
 try{real=window.localStorage}catch(e){return}
 if(!real)return;
 var ours=function(){return Object.keys(real).filter(function(k){return k.indexOf(PREFIX)===0})};
 var facade={
  getItem:function(k){return real.getItem(PREFIX+k)},
  setItem:function(k,v){return real.setItem(PREFIX+k,v)},
  removeItem:function(k){return real.removeItem(PREFIX+k)},
  clear:function(){ours().forEach(function(k){real.removeItem(k)})},
  key:function(i){var k=ours()[i];return k===undefined?null:k.slice(PREFIX.length)},
  get length(){return ours().length}
 };
 try{Object.defineProperty(window,'localStorage',{configurable:true,get:function(){return facade}})}
 catch(e){/* An older browser keeps the shared store; the banner still says this is a preview. */}
})();
